sudo: required
dist: trusty
before_install:
- sudo add-apt-repository ppa:jonathonf/texlive -y
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended texlive-luatex texlive-xetex latex-xcolor texlive-pictures pgf texlive-lang-french fonts-font-awesome xzdec
script:
- latexmk -cd -f -pdflatex=lualatex -interaction=nonstopmode -synctex=1 -pdf cv.tex
deploy:
  provider: releases
  api_key:
    secure: <key from travis CLI script>
  file:
  - resume.pdf
  skip_cleanup: true
  on:
    tags: true