version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Git installation
          command: apt-get -qq update; apt-get -y install git
      - add_ssh_keys
      - checkout
      - run:
          name: build
          command: latexmk -cd -f -lualatex -interaction=nonstopmode -synctex=1 cv.tex
      - run:
          name: Print the Current Time
          command: date
